"""Create or update a .env file with OS and CI defaults."""
from __future__ import annotations

import argparse
import os
import platform
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ENV_EXAMPLE = ROOT / ".env.example"
ENV_FILE = ROOT / ".env"


def detect_os() -> str:
    sys_name = platform.system().lower()
    if sys_name.startswith("win"):
        return "windows"
    if sys_name.startswith("darwin"):
        return "macos"
    return "linux"


def detect_ci() -> str:
    if os.environ.get("GITHUB_ACTIONS") == "true":
        return "github"
    if os.environ.get("GITLAB_CI") == "true":
        return "gitlab"
    return "none"


def parse_env(text: str) -> dict[str, str]:
    data: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        data[key] = value
    return data


def serialize_env(data: dict[str, str]) -> str:
    ordered_keys = [
        "LYCO_OS",
        "LYCO_CI_PROVIDER",
        "LYCO_PYTHON",
        "LYCO_VENV",
        "RUN_SAFETY",
        "RUN_SBOM",
        "RUN_BANDIT",
        "RUN_SEMGREP",
        "RUN_SECRET_SCAN",
        "RUN_LOCAL_CI",
        "CI_GUARD_DAYS",
        "CI_GUARD_ALLOW",
        "SAFETY_API_KEY",
    ]
    lines = [
        f"# Generated by tools/setup_env.py on {datetime.now(timezone.utc).isoformat()}",
    ]
    for key in ordered_keys:
        if key in data:
            lines.append(f"{key}={data[key]}")
    for key in sorted(k for k in data if k not in ordered_keys):
        lines.append(f"{key}={data[key]}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Configure .env for Lyco Python Framework.")
    parser.add_argument("--os", default="auto", choices=["auto", "windows", "macos", "linux"])
    parser.add_argument("--ci", default="auto", choices=["auto", "github", "gitlab", "none"])
    parser.add_argument("--python", dest="python_path", default="")
    parser.add_argument("--venv", dest="venv_path", default=".venv")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    base = parse_env(ENV_EXAMPLE.read_text(encoding="utf-8")) if ENV_EXAMPLE.exists() else {}
    if ENV_FILE.exists():
        base.update(parse_env(ENV_FILE.read_text(encoding="utf-8")))

    chosen_os = detect_os() if args.os == "auto" else args.os
    chosen_ci = detect_ci() if args.ci == "auto" else args.ci

    base["LYCO_OS"] = chosen_os
    base["LYCO_CI_PROVIDER"] = chosen_ci
    base["LYCO_PYTHON"] = args.python_path
    base["LYCO_VENV"] = args.venv_path

    if chosen_os == "windows":
        base["RUN_SEMGREP"] = "0"
    else:
        base["RUN_SEMGREP"] = "1"

    content = serialize_env(base)
    if args.dry_run:
        print(content)
        return 0

    ENV_FILE.write_text(content, encoding="utf-8")
    print(f"Wrote {ENV_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
